/**
 * action 类型
 * loopcf create by 2017-04-16
 */


//读取鼠绘漫画列表
export const LOAD_SHUHUI_LIST = "LOAD_SHUHUI_LIST";
//得到鼠绘漫画列表
export const GET_SHUHUI_LIST = "GET_SHUHUI_LIST";
//刷新鼠绘漫画列表
export const RESET_SHUHUI_LIST = "RESET_SHUHUI_LIST";

// 发现

//读取发现列表
export const LOAD_DISCOVERY_LIST = "LOAD_DISCOVERY_LIST";
//得到发现列表
export const GET_DISCOVERY_LIST = "GET_DISCOVERY_LIST";
//刷新
export const RESET_DISCOVERY_LIST = "RESET_DISCOVERY_LIST";

//读取国产漫画列表
export const LOAD_DOMESTIC_LIST = "LOAD_DOMESTIC_LIST";
//得到国产漫画列表
export const GET_DOMESTIC_LIST = "GET_DOMESTIC_LIST";
//刷新国产漫画列表
export const RESET_DOMESTIC_LIST = "RESET_DOMESTIC_LIST";

//读取热血漫画列表
export const LOAD_PASSION_LIST = "LOAD_PASSION_LIST";
//得到热血漫画列表
export const GET_PASSION_LIST = "GET_PASSION_LIST";
//刷新热血漫画列表
export const RESET_PASSION_LIST = "RESET_PASSION_LIST";
// 章节列表

export const LOAD_CHAPTER_LIST = "LOAD_CHAPTER_LIST";
export const GET_CHAPTER_LIST = "GET_CHAPTER_LIST";
export const RESET_CHAPTER_LIST = "RESET_CHAPTER_LIST";

// 漫画详情

export const LOAD_COMBICK_DETIAL_LIST = "LOAD_COMBICK_DETIAL_LIST";
export const GET_COMBICK_DETIAL_LIST = "GET_COMBICK_DETIAL_LIST";
export const RESET_COMBICK_DETIAL_LIST = "RESET_COMBICK_DETIAL_LIST";

// 收藏

export const LOAD_COLLECTION_LIST = "LOAD_COLLECTION_LIST";
export const GET_COLLECTION_LIST = "GET_COLLECTION_LIST";
export const RESET_COLLECTION_LIST = "RESET_COLLECTION_LIST";


// for user
export const AUTH_USER = 'auth_user';
export const UNAUTH_USER = 'unauth_user';
export const AUTH_ERROR = 'auth_error';
export const FETCH_MESSAGE = 'fetch_message';


export const FETCH_KEYWORDS_LIST = 'FETCH_KEYWORDS_LIST';
export const RECEIVE_KEYWORDS_LIST = 'RECEIVE_KEYWORDS_LIST';
export const SELECT_KEYWORD = 'SELECT_KEYWORD';
export const RESET_SEARCH_STATE = 'RESET_SEARCH_STATE';
export const CACHE_HISTORY = 'CACHE_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const SETUP_SEARCH_TEXT = 'SETUP_SEARCH_TEXT';
export const FETCH_SEARCH_RESULT_LIST = 'FETCH_SEARCH_RESULT_LIST';
export const RECEIVE_SEARCH_RESULT_LIST = 'RECEIVE_SEARCH_RESULT_LIST';

export const CHANGE_HEALTH_LIGHT_SEARCH = 'CHANGE_HEALTH_LIGHT_SEARCH';
export const SELECT_RECOMMEND_TAG = 'SELECT_RECOMMEND_TAG';
export const FETCH_CATEGORY_LIST = 'FETCH_CATEGORY_LIST';
export const RECEIVE_CATEGORY_LIST = 'RECEIVE_CATEGORY_LIST';
export const RECEIVE_NET_INFO = 'RECEIVE_NET_INFO';
export const SEARCH_NET_INFO = 'SEARCH_NET_INFO';
export const FETCH_MESSAGE_LIST = 'FETCH_MESSAGE_LIST';
export const RECEIVE_MESSAGE_LIST = 'RECEIVE_MESSAGE_LIST';
